-- Aggregated Data Model for Glance Platform — POINTER
--
-- The runnable schema is now maintained as a migration in the backend, so there is a
-- single source of truth (this file previously drifted: it used the `public` schema and a
-- UUID users.id, but the deployment uses the `api` schema and a TEXT Clerk user id):
--
--     backend/db/migrations/0001_init_schema.sql      (apply with: npm run db:migrate)
--
-- For the conceptual model and entity relationships (ERD), see:
--
--     specs/plan/data-model.md
